# Generated by Django 6.0.3 on 2026-03-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_item_discount_alter_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
