# Generated by Django 6.0.1 on 2026-03-23 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_action_item_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.action'),
        ),
    ]
