# Generated by Django 6.0.3 on 2026-03-26 06:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Incorrect phone number format', regex='^07\\d{8}$')])),
                ('id_number', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Invalid ID format', regex='^\\d{7,8}$')])),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
