# Generated by Django 6.0.3 on 2026-03-15 07:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be in format 07XX XXX XXX.', regex='^07\\d{8}$')])),
                ('id_no', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Incorrect ID number format.', regex='^\\d{7,8}$')])),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_start', models.DateField()),
                ('contract_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Center Back'), ('RB', 'Right Back'), ('LB', 'Left Back'), ('DMF', 'Defensive Midfielder'), ('CMF', 'Center Midfielder'), ('AMF', 'Attacking Midfielder'), ('SS', 'Second Striker'), ('CF', 'Centre Forward')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(choices=[('ACROBATIC_CLEARANCES', 'Acrobatic Clearances'), ('SLIDING_TACKLE', 'Sliding Tackle'), ('STANDING_TACKLE', 'Sanding Tackle'), ('HEADING', 'Heading'), ('SUPER_JUMP', 'Super Jump'), ('BULLET_HEADER', 'Bullet Header'), ('BLITZ_CURL', 'Blitz Curl'), ('EDGED_CROSSING', 'Edged Crossing'), ('OUTSIDE_CURL', 'Outside Curl'), ('CHIP_SHOT', 'Chip Shot')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be in format 07XX XXX XXX.', regex='^07\\d{8}$')])),
                ('id_no', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='Incorrect ID number format.', regex='^\\d{7,8}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.CharField(choices=[('BENCH', 'Bench'), ('SUBSTITUTE', 'Substitute'), ('STARTING_11', 'Starting_11')])),
                ('club_before', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_players', to='apps.club')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='apps.coach')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.contract')),
                ('current_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_players', to='apps.club')),
                ('player_position', models.ManyToManyField(to='apps.position')),
                ('skills', models.ManyToManyField(to='apps.skills')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
