# Generated by Django 6.0.1 on 2026-03-17 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_coach_user_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.coach'),
        ),
    ]
