# Generated by Django 6.0.1 on 2026-03-18 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_contract_salary_alter_player_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.contract'),
        ),
    ]
