# Generated by Django 5.2.9 on 2026-03-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_grade_id_alter_student_adm_alter_subject_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='adm',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
